spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/prodcat_db
    username: root
    password: aidar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    org.springframework.security: DEBUG