spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/prodcat_db
    username: root
    password: aidar
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  security:
    jdbc:
      authentication:
        enabled: false
logging:
  level:
    org.springframework.security: DEBUG