spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/prodcat_db
    username: root
    password: aidar
  jpa:
    hibernate:
      ddl-auto: update # or 'create' or 'validate'
    show-sql: true
