spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/prodcat_db
    username: root
    password: aidar
  jpa:
    hibernate:
      ddl-auto: update # ou 'create' ou 'validate'
    show-sql: true
  debug: true
