spring:
    config:
      activate:
        on-profile: prod
    datasource:
      url: jdbc:mariadb://localhost:3306/prodcat_db
      username: root
      password: aidar
    jpa:
      hibernate:
        ddl-auto: validate
    security:
      jdbc:
        authentication:
          enabled: true