spring:
  config:
    activate:
      on-profile: prod
  datasource:
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    jdbc:
      authentication:
        enabled: true